### ISSUE TITLE
寿司打でキー入力のタイミングでブラウザが落ちる

### ISSUE THREAD

**Issue by shota-watanabe** [chen-196-hub/auto_sushida#12]
@chen-196-hub 
```ruby
ruby auto_shshida.rb h
```
- ブラウザが開き、高級コースを選択してゲームが始まるが、入力が始まるタイミングでブラウザが落ち、ターミナルに下記のようなエラーが出ます。
```ruby
Traceback (most recent call last):
        4: from auto_shshida.rb:37:in `<main>'
        3: from auto_shshida.rb:37:in `require_relative'
        2: from /Users/watasho/hobby/auto_sushida/image_cutter.rb:1:in `<top (required)>'
        1: from /Users/watasho/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/Users/watasho/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- mini_magick (LoadError)
```

**Comment by chen-196-hub** [comment]
@shota-watanabe 
リクエストありがとうございます！
とりあえずの対策としては、ルートフォルダに下記の画像を`page.png`名にしたら解消されるかと思います。
![page](https://user-images.githubusercontent.com/78460152/203676832-d128aabb-8bff-4e71-8801-3e2378ac3dd4.png)

この件についてはまた修正対応します！

**Comment by chen-196-hub** [comment]
```ruby
        1: from /Users/watasho/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/Users/watasho/.rbenv/versions/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- mini_magick (LoadError)
```

この行で、`require 'mini_magick'`するとき問題が起きてるっぽい
https://stackoverflow.com/questions/16108152/minimagick-cannot-load-such-file
とりあえず参考記事送ります。railsの場合再起動で解決できるっぽい？
もうちょっと調べてみますね！
